FROM nginx:1.15.8-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./*.html /usr/share/nginx/html/
COPY ./*.js /usr/share/nginx/html/
COPY ./*.png /usr/share/nginx/html/
COPY ./*.css /usr/share/nginx/html/
COPY ./*.gif /usr/share/nginx/html/
